### ISSUE TITLE
Node telnet.js won't launch

### ISSUE THREAD

**Issue by Yozine** [silentrob/hello-superscript#1]
I run into this error. 
Version of Node is 0.12.13, under Ubuntu 14.04LTS

alice@ubuntu:~/hello-superscript-master$ ./node_modules/superscript/bin/cleanup.js --mongo telnetbot
users is clear
topics is clear
replies is clear
gambits is clear
Time to Process 2.044 seconds
Number of topics 2 parsed.
Number of gambits 2 parsed.
Number of replies 2 parsed.
Number of convos 0 parsed.
Number of Replies: 0
Number of Gambits: 0
Everything imported
alice@ubuntu:~/hello-superscript-master$ node telnet.js

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/alice/hello-superscript-master/node_modules/superscript/node_modules/node-normalizer/node_modules/re2/build/Release/re2.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/alice/hello-superscript-master/node_modules/superscript/node_modules/node-normalizer/node_modules/re2/re2.js:3:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Yozine** [comment]
Got this working.
